import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/Navbar';
import AppWalletProvider from "./components/AppWalletProvider";
import { cn } from "@/utils/helper";
import { UserProvider } from "@/context/UserContext";
import 'react-toastify/dist/ReactToastify.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full w-full m-auto md:w-3/4 lg:w-3/4", inter.className)} data-theme="cupcake">
      <body className="flex flex-col h-full">
        <AppWalletProvider>
          <UserProvider>
            <Navbar />
            <main className="flex-1">
              {children}
            </main>
          </UserProvider>
        </AppWalletProvider>
      </body>
    </html>
  );
}
